### ISSUE TITLE
When accesses LightNode2-Pre Swagger, throwed an InvalidOperationException.

### ISSUE THREAD

**Issue by NitaCore** [neuecc/LightNode#59]
Steps to reproduce:
  1.Start LightNode-Pre with swagger
  2.Access http://localhost:15944/swagger/

ExceptionMessage:
  Headers are read-only, response has already started.

**Comment by neuecc** [comment]
Thank you, fixed by #60 and I've uploaded 2.0.1.

**Comment by NitaCore** [comment]
Thanks!
